exports.AccountStatus = Object.freeze({
  Normal: 'Normal',
  Suspended: 'Suspended',
  Locked: 'Locked',
  WrongPassword: 'Wrong Password',
  NetworkError: 'Network Error',
  UnknownError: 'Unknown Error',
  WrongCaptcha: 'Wrong Captcha',
  EmailVerify: 'Email Verify',
  PhoneVerify: 'Phone Verify',
  FAVerify: 'FA Verify',
  PasswordChangeRequired: 'Password Change Required',
  WrongUserAgent: 'Wrong User Agent',
  BindingSuccess: 'Binding Success',
  BindingFailure: 'Binding Failure',
});
